Fix padding calculation for large AADs in xchacha20poly1305 secretstream push/pull
brndnmtthws/dryoc pull request #73
Opened 2024-12-05 17:50 UTC by httpjamesm

* Uses the correct modulo calculation when updating the mac:

` mac.update(&_pad0[..((0x10 - (associated_data.len() % 0x10)) & 0xf)]);`

Previous code did not include the modulus, thus failing on AADs larger than 16 bytes. The XChaCha20 specification allows much more than that.

The original libsodium implementation in C does a similar operation:

```c
    crypto_onetimeauth_poly1305_update(&poly1305_state, _pad0,
                                       (0x10 - adlen) & 0xf);
```

* Adds a unit test to ensure large AAD works

```
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.32s
     Running unittests src/lib.rs (/home/james/Develop/dryoc/target/debug/deps/dryoc-fc575e74639062ec)

running 1 test
test classic::crypto_secretstream_xchacha20poly1305::tests::test_secretstream_large_aad ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 87 filtered out; finished in 0.00s
```

Without the fix, it fails

2024-12-06 12:39 UTC, brndnmtthws requested changes
A couple minor suggestions, but otherwise it looks good.

2024-12-06 12:44 UTC, brndnmtthws commented
For anyone reading, here's more detail on the bug: this would only fail in debug mode, but not release mode. In release mode, it will silently succeed. Here's a simple demonstration of the problem: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=af06abf7079edb5b16fc860693102d71

While libsodium's implementation is technically wrong, it works fine because C isn't fussy about the overflow, but Rust is strict.

For reference, the padding is described in RFC 7539 here: https://datatracker.ietf.org/doc/html/rfc7539#section-2.8.1

In terms of security risk, this is pretty innocuous but still worth fixing.

2024-12-06 13:27 UTC, brndnmtthws commented
I did some housekeeping, you'll need to rebase against `main`.

2024-12-06 19:57 UTC, httpjamesm commented
Changes addressed :+1:

2024-12-07 13:34 UTC, brndnmtthws approved these changes
Very nice, thank you kindly!

2024-12-07 13:48 UTC, merged